language: perl6
perl6:
  - latest
install:
  - rakudobrew build-panda ${TRAVIS_PERL6_VERSION#latest}
  - panda installdeps .
  - panda install Test::META
script:
  - PERL6_TEST_META=1 PERL6LIB=$PWD/lib prove -e perl6 -r t/
sudo: false
